# ---- Build data ----
# ONS geoportal query urls can be found on the "API Explorer" tab.
query_urls <-
  tibble::tribble(
    # Column Names
    ~data_set                                     , ~type        , ~notes                                                                                                                          , ~query_url                                                                                                                                                                                                                                                                                                                                                            , ~source                                                                                                                                                                         ,

    # Deprivation - latest indices
    # England
    "imd2025_england_lsoa21"                      , "imd"        , "File 7: All ranks, scores, deciles and population denominators for the Indices of Deprivation (including subdomains)"          , "https://assets.publishing.service.gov.uk/media/68ff5daabcb10f6bf9bef911/File_7_IoD2025_All_Ranks_Scores_Deciles_Population_Denominators.csv"                                                                                                                                                                                                                         , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2025"                                                                                                  ,
    "imd2025_england_lsoa21_indicators"           , "imd"        , "File 8: Underlying indicators"                                                                                                 , "https://assets.publishing.service.gov.uk/media/6900df8dab5cc9c8937994e6/File_8_IoD2025_Underlying_Indicators.xlsx"                                                                                                                                                                                                                                                   , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2025"                                                                                                  ,
    "imd2025_england_ltla24"                      , "imd"        , "File 10: Local Authority District summaries - lower tier"                                                                      , "https://assets.publishing.service.gov.uk/media/68ff7e26d81972ecd2df5db1/File_10_-_IoD2025_Local_Authority_District_Summaries__lower-tier_.xlsx"                                                                                                                                                                                                                      , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2025"                                                                                                  ,
    "imd2025_england_icb"                         , "imd"        , "File 13: Integrated Care Board summaries"                                                                                      , "https://assets.publishing.service.gov.uk/media/68ff7ed00f801e57b5bef928/File_13_-_IoD2025_Integrated_Care_Board__ICB__Summaries.xlsx"                                                                                                                                                                                                                                , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2025"                                                                                                  ,
    "imd2025_england_lrf"                         , "imd"        , "File 14: Local Resilience Forum summaries"                                                                                     , "https://assets.publishing.service.gov.uk/media/68ff7eecbcb10f6bf9bef925/File_14_-_IoD2025_Local_Resilience_Forum__LRG__Summaries.xlsx"                                                                                                                                                                                                                               , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2025"                                                                                                  ,

    "imd_lsoa_england"                            , "imd"        , "LSOA-level deprivation in England"                                                                                             , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/845345/File_7_-_All_IoD2019_Scores__Ranks__Deciles_and_Population_Denominators_3.csv"                                                                                                                                                                                , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019"                                                                                                  ,
    "imd_lad_england"                             , "imd"        , "Local Authority deprivation in England"                                                                                        , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/833995/File_10_-_IoD2019_Local_Authority_District_Summaries__lower-tier__.xlsx"                                                                                                                                                                                      , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019"                                                                                                  ,
    "imd_england_subdomains"                      , "imd"        , "Sub-domains of LSOA-level deprivation in England"                                                                              , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/833976/File_4_-_IoD2019_Sub-domains_of_Deprivation.xlsx"                                                                                                                                                                                                             , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019"                                                                                                  ,
    "imd_england_indicators"                      , "imd"        , "File 8: underlying indicators"                                                                                                 , "https://assets.publishing.service.gov.uk/media/5d8b3cd740f0b609909b590a/File_8_-_IoD2019_Underlying_Indicators.xlsx"                                                                                                                                                                                                                                                 , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019"                                                                                                  ,
    # Wales
    "imd_lsoa_wales"                              , "imd"        , "LSOA-level deprivation in Wales"                                                                                               , "https://www.gov.wales/sites/default/files/statistics-and-research/2022-02/welsh-index-multiple-deprivation-2019-index-and-domain-ranks-by-small-area.ods"                                                                                                                                                                                                            , "https://gov.wales/welsh-index-multiple-deprivation-full-index-update-ranks-2019"                                                                                               ,
    "imd_lsoa_wales_scores"                       , "imd"        , "LSOA-level deprivation scores in Wales"                                                                                        , "https://www.gov.wales/sites/default/files/statistics-and-research/2022-02/wimd-2019-index-and-domain-scores-by-small-area.ods"                                                                                                                                                                                                                                       , "https://gov.wales/welsh-index-multiple-deprivation-full-index-update-ranks-2019"                                                                                               ,
    # Scotland
    "imd_dz_scotland"                             , "imd"        , "DZ-level deprivation in Scotland"                                                                                              , "https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/01/scottish-index-of-multiple-deprivation-2020-ranks-and-domain-ranks/documents/scottish-index-of-multiple-deprivation-2020-ranks-and-domain-ranks/scottish-index-of-multiple-deprivation-2020-ranks-and-domain-ranks/govscot%3Adocument/SIMD_2020_Ranks_and_Domain_Ranks.xlsx" , "https://simd.scot"                                                                                                                                                             ,
    "imd2020_dz11_scotland_indicators"            , "imd"        , "Scottish Index of Multiple Deprivation 2020v2 - indicators"                                                                    , "https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/01/scottish-index-of-multiple-deprivation-2020-indicator-data/documents/simd_2020_indicators/simd_2020_indicators/govscot%3Adocument/SIMD%2B2020v2%2B-%2Bindicators.xlsx"                                                                                                       , "https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020v2-indicator-data/"                                                                               ,
    # NI
    "imd_soa_ni"                                  , "imd"        , "SOA-level deprivation in Northern Ireland"                                                                                     , "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/NIMDM17_SOAresults.xls"                                                                                                                                                                                                                                                                               , "https://www.nisra.gov.uk/statistics/deprivation/northern-ireland-multiple-deprivation-measure-2017-nimdm2017"                                                                  ,
    # UK-wide version
    "imd_uk_e"                                    , "imd"        , "Composite 2020 UK Index of Multiple Deprivation: England"                                                                      , "https://github.com/mysociety/composite_uk_imd/raw/main/data/uk_index/UK_IMD_E.csv"                                                                                                                                                                                                                                                                                   , "https://github.com/mysociety/composite_uk_imd"                                                                                                                                 ,
    "imd_uk_w"                                    , "imd"        , "Composite 2020 UK Index of Multiple Deprivation: Wales"                                                                        , "https://github.com/mysociety/composite_uk_imd/raw/main/data/uk_index/UK_IMD_W.csv"                                                                                                                                                                                                                                                                                   , "https://github.com/mysociety/composite_uk_imd"                                                                                                                                 ,
    "imd_uk_s"                                    , "imd"        , "Composite 2020 UK Index of Multiple Deprivation: Scotland"                                                                     , "https://github.com/mysociety/composite_uk_imd/raw/main/data/uk_index/UK_IMD_S.csv"                                                                                                                                                                                                                                                                                   , "https://github.com/mysociety/composite_uk_imd"                                                                                                                                 ,
    "imd_uk_n"                                    , "imd"        , "Composite 2020 UK Index of Multiple Deprivation: NI"                                                                           , "https://github.com/mysociety/composite_uk_imd/raw/main/data/uk_index/UK_IMD_N.csv"                                                                                                                                                                                                                                                                                   , "https://github.com/mysociety/composite_uk_imd"                                                                                                                                 ,

    # Deprivation - historical indices
    # England
    "imd2000_ward98_england"                      , "imd"        , "Indices of Deprivation 2000: Ward indices"                                                                                     , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407204456mp_/http://www.communities.gov.uk/documents/citiesandregions/xls/131294.xls"                                                                                                                                                                                                                          , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407204456/http://www.communities.gov.uk/archived/general-content/communities/indicesofdeprivation/indicesofdeprivation/" ,
    "imd2004_lsoa01_england"                      , "imd"        , "SOA Level ID 2004"                                                                                                             , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407164233mp_/http://www.communities.gov.uk/documents/communities/zip/soalevelid.zip"                                                                                                                                                                                                                           , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407164233/http://www.communities.gov.uk/archived/general-content/communities/indicesofdeprivation/216309/"               ,
    "imd2007_lsoa01_england"                      , "imd"        , "Indices of Multiple Deprivation 2007"                                                                                          , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100411141238mp_/http://www.communities.gov.uk/documents/communities/zip/indices2007.zip"                                                                                                                                                                                                                          , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100411141238/http://www.communities.gov.uk/communities/neighbourhoodrenewal/deprivation/deprivation07/"                     ,
    "imd2010_lsoa01_england"                      , "imd"        , " English indices of deprivation 2010: all domains, all sub domains and supplementary indices"                                  , "https://assets.publishing.service.gov.uk/media/5a78b02440f0b62b22cbbfe9/1871702.csv"                                                                                                                                                                                                                                                                                 , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2010"                                                                                                  ,
    "imd2010_lad09_england"                       , "imd"        , "English indices of deprivation 2010: local authority summaries"                                                                , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/6884/1871689.xls"                                                                                                                                                                                                                                                    , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2010"                                                                                                  ,
    "imd2015_lsoa11_england"                      , "imd"        , "File 1: index of multiple deprivation"                                                                                         , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/467764/File_1_ID_2015_Index_of_Multiple_Deprivation.xlsx"                                                                                                                                                                                                            , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2015"                                                                                                  ,
    "imd2015_lsoa11_england_scores"               , "imd"        , "File 5: scores for the indices of deprivation"                                                                                 , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/467768/File_5_ID_2015_Scores_for_the_Indices_of_Deprivation.xlsx"                                                                                                                                                                                                    , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2015"                                                                                                  ,
    # Scotland
    "imd2016_dz_scotland"                         , "imd"        , "DZ-level deprivation in Scotland"                                                                                              , "https://webarchive.nrscotland.gov.uk/20190708060827mp_/https://www2.gov.scot/Resource/0053/00534450.xlsx"                                                                                                                                                                                                                                                            , "https://webarchive.nrscotland.gov.uk/20190708060827/https://www2.gov.scot/Topics/Statistics/SIMD"                                                                              ,
    "imd2016_dz11_scotland_indicators"            , "imd"        , "SIMD16 indicator data"                                                                                                         , "https://webarchive.nrscotland.gov.uk/20190708060827mp_/https://www2.gov.scot/Resource/0053/00534452.xlsx"                                                                                                                                                                                                                                                            , "https://webarchive.nrscotland.gov.uk/20190708060827/https://www2.gov.scot/Topics/Statistics/SIMD"                                                                              ,
    "imd2012_dz01_scotland"                       , "imd"        , "SIMD 2012 Data - Overall rank and domain rank"                                                                                 , "https://web.archive.org/web/20130201182625/http://www.scotland.gov.uk/Resource/0041/00410767.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_income"     , "imd"        , "SIMD 2012 Data - Income domain"                                                                                                , "https://web.archive.org/web/20130201182628/http://www.scotland.gov.uk/Resource/0041/00410768.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_employment" , "imd"        , "SIMD 2012 Data - Employment domain"                                                                                            , "https://web.archive.org/web/20130201182630/http://www.scotland.gov.uk/Resource/0041/00410769.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_health"     , "imd"        , "SIMD 2012 Data - Health domain"                                                                                                , "https://web.archive.org/web/20130201182633/http://www.scotland.gov.uk/Resource/0041/00410770.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_education"  , "imd"        , "SIMD 2012 Data - Education domain"                                                                                             , "https://web.archive.org/web/20130201182635/http://www.scotland.gov.uk/Resource/0041/00413502.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_housing"    , "imd"        , "SIMD 2012 Data - Housing domain"                                                                                               , "https://web.archive.org/web/20130201182637/http://www.scotland.gov.uk/Resource/0041/00410772.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_access"     , "imd"        , "SIMD 2012 Data - Access domain"                                                                                                , "https://web.archive.org/web/20130201182640/http://www.scotland.gov.uk/Resource/0041/00410773.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    "imd2012_dz01_scotland_indicators_crime"      , "imd"        , "SIMD 2012 Data - Crime domain"                                                                                                 , "https://web.archive.org/web/20130201182642/http://www.scotland.gov.uk/Resource/0041/00410775.xls"                                                                                                                                                                                                                                                                    , "https://web.archive.org/web/20130204090839/http://www.scotland.gov.uk/Topics/Statistics/SIMD/DataAnalysis/Background-Data-2012"                                                ,
    # Wales
    "imd2011_lsoa_wales"                          , "imd"        , "LSOA-level deprivation in Wales"                                                                                               , "https://www.gov.wales/sites/default/files/statistics-and-research/2019-04/wimd-2011-individual-domain-scores-and-overall-index-scores-for-each-lsoa.xls"                                                                                                                                                                                                             , "https://www.gov.wales/welsh-index-multiple-deprivation-full-index-update-ranks-2011"                                                                                           ,
    # NI
    "imd2010_soa_ni"                              , "imd"        , "SOA-level deprivation in NI"                                                                                                   , "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/Copy%20of%20NIMDM_2010_Results_SOA_0.xls"                                                                                                                                                                                                                                                             , "https://www.nisra.gov.uk/publications/nothern-ireland-multiple-deprivation-measure-2010-soa-results"                                                                           ,

    # Household-level deprivation from Census(es)
    "census11_deprivation_ni_lgd14"               , "imd"        , "Household deprivation"                                                                                                         , "https://www.nisra.gov.uk/system/files/statistics/census-2011-commissioned-table-ct0590ni.xlsx"                                                                                                                                                                                                                                                                       , "https://www.nisra.gov.uk/statistics/2011-census/results/commissioned-output"                                                                                                   ,
    "census21_deprivation_ni_lgd14"               , "imd"        , "Household deprivation"                                                                                                         , "https://build.nisra.gov.uk/en/custom/table.csv?d=HOUSEHOLD&v=LGD14&v=HH_DEPRIVATION"                                                                                                                                                                                                                                                                                 , "https://build.nisra.gov.uk/en/custom/data?d=HOUSEHOLD&v=LGD14&v=HH_DEPRIVATION"                                                                                                ,
    "census21_deprivation_ni_sdz21"               , "imd"        , "Household deprivation"                                                                                                         , "https://build.nisra.gov.uk/en/custom/table.csv?d=HOUSEHOLD&v=SDZ21&v=HH_DEPRIVATION"                                                                                                                                                                                                                                                                                 , "https://build.nisra.gov.uk/en/custom/data?d=HOUSEHOLD&v=SDZ21&v=HH_DEPRIVATION"                                                                                                ,

    # Lookups
    "lsoa_msoa_lad"                               , "lookup"     , "Output Area to LSOA to MSOA to Local Authority District (December 2017) Lookup with Area Classifications in Great Britain"     , "https://opendata.arcgis.com/datasets/fe6c55f0924b4734adf1cf7104a0173e_0.csv"                                                                                                                                                                                                                                                                                         , "http://geoportal.statistics.gov.uk/datasets/fe6c55f0924b4734adf1cf7104a0173e_0"                                                                                                ,
    "lsoa_ward"                                   , "lookup"     , "Lower Layer Super Output Area (2011) to Ward (2019) Lookup in England and Wales"                                               , "https://opendata.arcgis.com/datasets/15299a7b8e6c498d94a08b687c75b73f_0.csv"                                                                                                                                                                                                                                                                                         , "https://geoportal.statistics.gov.uk/datasets/lower-layer-super-output-area-2011-to-ward-2019-lookup-in-england-and-wales"                                                      ,
    "msoa_lad"                                    , "lookup"     , "Middle Layer Super Output Area (2011) to Ward to LAD (December 2019)"                                                          , "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/MSOA11_WD19_LAD19_EW_LU/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json"                                                                                                                                                                                                          , "https://geoportal.statistics.gov.uk/datasets/0b3c76d1eb5e4ffd98a3679ab8dea605_0/geoservice"                                                                                    ,
    "dz_iz_lad"                                   , "lookup"     , "Data zone to intermediate zone and local authority in Scotland"                                                                , "https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2020/01/scottish-index-of-multiple-deprivation-2020-data-zone-look-up-file/documents/scottish-index-of-multiple-deprivation-data-zone-look-up/scottish-index-of-multiple-deprivation-data-zone-look-up/govscot%3Adocument/SIMD_2020_Datazone_lookup_tool.xlsx"                       , "https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020-data-zone-look-up/"                                                                              ,
    "sa_soa_lgd"                                  , "lookup"     , "Small Areas (2011) to SOAs to Local Government Districts (December 2018) Lookup with Area Classifications in Northern Ireland" , "https://opendata.arcgis.com/datasets/096a7ccbc8e244cc972189b2f07a321a_0.csv"                                                                                                                                                                                                                                                                                         , "https://geoportal.statistics.gov.uk/datasets/small-areas-2011-to-soas-to-local-government-districts-december-2018-lookup-with-area-classifications-in-northern-ireland"        ,
    "lsoa01_lsoa11"                               , "lookup"     , "Lower Layer Super Output Area (2001) to Lower Layer Super Output Area (2011) lookup"                                           , "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LSOA01_LSOA11_LAD11_EW_LU_ddfe1cd1c2784c9b991cded95bc915a9/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"                                                                                                                                                                               , "https://geoportal.statistics.gov.uk/datasets/ons::lsoa-2001-to-lsoa-2011-to-lad-december-2011-best-fit-lookup-in-ew/about"                                                     ,

    # Population estimates
    "pop_lsoa"                                    , "population" , "Lower layer Super Output Area population estimates: mid-2019"                                                                  , "https://www.ons.gov.uk/file?uri=%2fpeoplepopulationandcommunity%2fpopulationandmigration%2fpopulationestimates%2fdatasets%2flowersuperoutputareamidyearpopulationestimates%2fmid2019sape22dt2/sape22dt2mid2019lsoasyoaestimatesunformatted.zip"                                                                                                                      , "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/lowersuperoutputareamidyearpopulationestimates"                        ,
    "pop_dz"                                      , "population" , "Scotland Data Zone population estimates: mid-2019"                                                                             , "https://www.opendata.nhs.scot/datastore/dump/c505f490-c201-44bd-abd1-1bd7a64285ee?bom=True"                                                                                                                                                                                                                                                                          , "https://www.opendata.nhs.scot/dataset/population-estimates/resource/c505f490-c201-44bd-abd1-1bd7a64285ee"                                                                      ,
    "pop_soa"                                     , "population" , "Northern Ireland Super Output Area population estimates: mid-2019"                                                             , "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/MYE19_SOA_WARD.xlsx"                                                                                                                                                                                                                                                                                  , "https://www.nisra.gov.uk/publications/2019-mid-year-population-estimates-northern-ireland"                                                                                     ,
    "pop15_lsoa"                                  , "population" , "Population denominators for IMD 2015"                                                                                          , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/467773/File_6_ID_2015_Population_denominators.xlsx"                                                                                                                                                                                                                  , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2015"                                                                                                  ,
    "pop10_lsoa"                                  , "population" , "English indices of deprivation 2010: population denominators (mid-2008)"                                                       , "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/15243/1981232.xls"                                                                                                                                                                                                                                                   , "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2010"                                                                                                  ,
    "pop07_lsoa"                                  , "population" , "mid-2005 population estimates used in constructing the Indices of Multiple Deprivation 2007"                                   , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407164210mp_/http://www.communities.gov.uk/documents/communities/xls/708341.xls"                                                                                                                                                                                                                               , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407164210/http://www.communities.gov.uk/communities/neighbourhoodrenewal/deprivation/deprivation07/mid2005population/"   ,
    "pop04_lsoa"                                  , "population" , "SOA level 2001 population estimates - rounded"                                                                                 , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407164233mp_/http://www.communities.gov.uk/documents/communities/xls/soalevel2001.xls"                                                                                                                                                                                                                         , "https://webarchive.nationalarchives.gov.uk/ukgwa/20100407164233/http://www.communities.gov.uk/archived/general-content/communities/indicesofdeprivation/216309/"
  )

usethis::use_data(query_urls, internal = TRUE, overwrite = TRUE)
